name: VSIX Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  package-vsix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
      - name: Build extension
        run: |
          npm --workspace apps/vscode-extension run build
      - name: Package VSIX
        run: |
          cd apps/vscode-extension
          npx @vscode/vsce package --no-yarn
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: elite-ai-agent-extension
          path: apps/vscode-extension/*.vsix
